### ISSUE TITLE
machine.restore_networking_configuration() causes aiohttp.client_exceptions.ServerDisconnectedError

### ISSUE THREAD

**Issue by djandruczyk** [maas/python-libmaas#255] opened 2021-03-05 23:47 UTC
With version 0.6.6 of python-libmaas against maas 2.9.2 installed from snap
```
~# snap list maas
Name  Version                 Rev    Tracking    Publisher   Notes
maas  2.9.2-9164-g.ac176b5c4  11851  2.9/stable  canonical✓  -
```

```
    machine.restore_networking_configuration()
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/maas/client/utils/maas_async.py", line 43, in wrapper
    result = eventloop.run_until_complete(result)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/maas/client/viscera/machines.py", line 796, in restore_networking_configuration
    await self._handler.restore_networking_configuration(
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/maas/client/bones/__init__.py", line 307, in __call__
    response = await self.bind(**params).call(**data)
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/maas/client/bones/__init__.py", line 459, in dispatch
    response = await session.request(
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/dandruczyk/libmaas/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

This is blocking us from using out automated tools to drive the maas API

**Comment by sparkiegeek** [comment] 2021-03-22 12:19
Duplicate of #251

**Closed by sparkiegeek** 2021-03-22 12:19 UTC
