### ISSUE TITLE
Resource pools can't be managed

### ISSUE THREAD

**Issue by juan-vg** [maas/python-libmaas#205] opened 2019-02-25 15:38 UTC
## Environment
python-libmaas==0.6.1
Python 3.6.7

## Problem
Pools can't be managed through the lib. [They can be managed via the API](https://docs.maas.io/2.5/en/api#resource-pool).

**Comment by albertodonato** [comment] 2019-05-21 17:30
This is a duplicate of #181

**Closed by albertodonato** 2019-05-21 17:30 UTC
